# Cleaning and Transforming Process

In [2]:
import polars as pd


df = pd.read_csv("./csic_database.csv")
df.describe()

shape: (9, 18)
┌────────────┬───────────┬────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆           ┆ Method ┆ User-Agent ┆ … ┆ lenght    ┆ content   ┆ classific ┆ URL       │
│ ---        ┆ ---       ┆ ---    ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ation     ┆ ---       │
│ str        ┆ str       ┆ str    ┆ str        ┆   ┆ str       ┆ str       ┆ ---       ┆ str       │
│            ┆           ┆        ┆            ┆   ┆           ┆           ┆ f64       ┆           │
╞════════════╪═══════════╪════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 61065     ┆ 61065  ┆ 61065      ┆ … ┆ 17977     ┆ 17977     ┆ 61065.0   ┆ 61065     │
│ null_count ┆ 0         ┆ 0      ┆ 0          ┆ … ┆ 43088     ┆ 43088     ┆ 0.0       ┆ 0         │
│ mean       ┆ null      ┆ null   ┆ null       ┆ … ┆ null      ┆ null      ┆ 0.410464  ┆ null      │
│ std        ┆ null      ┆ null   ┆ null       ┆ … ┆ null      ┆ null      ┆ 0.491922  ┆ null      │
│ min        ┆ Anomalous ┆ GET    ┆ Mozilla/5. ┆ … ┆ Content-L ┆ B2=%22%3E ┆ 0.0       ┆ http://lo │
│            ┆           ┆        ┆ 0 (compati ┆   ┆ ength:    ┆ %3C%21--% ┆           ┆ calhost:8 │
│            ┆           ┆        ┆ ble;       ┆   ┆ 100       ┆ 23EXEC+cm ┆           ┆ 080.BAK   │
│            ┆           ┆        ┆ Konqu…     ┆   ┆           ┆ d%3…      ┆           ┆ HTTP…     │
│ 25%        ┆ null      ┆ null   ┆ null       ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ null      │
│ 50%        ┆ null      ┆ null   ┆ null       ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ null      │
│ 75%        ┆ null      ┆ null   ┆ null       ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ null      │
│ max        ┆ Normal    ┆ PUT    ┆ Mozilla/5. ┆ … ┆ Content-L ┆ modoA=reg ┆ 1.0       ┆ http://lo │
│            ┆           ┆        ┆ 0 (compati ┆   ┆ ength: 99 ┆ istro&log ┆           ┆ calhost:8 │
│            ┆           ┆        ┆ ble;       ┆   ┆           ┆ in=yurchu ┆           ┆ 080~      │
│            ┆           ┆        ┆ Konqu…     ┆   ┆           ┆ k&p…      ┆           ┆ HTTP/1.…  │
└────────────┴───────────┴────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
df.schema

Schema([('', String),
        ('Method', String),
        ('User-Agent', String),
        ('Pragma', String),
        ('Cache-Control', String),
        ('Accept', String),
        ('Accept-encoding', String),
        ('Accept-charset', String),
        ('language', String),
        ('host', String),
        ('cookie', String),
        ('content-type', String),
        ('connection', String),
        ('lenght', String),
        ('content', String),
        ('classification', Int64),
        ('URL', String)])

In [4]:
# Show all columns on screen
with pd.Config(tbl_cols=17):
    print(df.null_count())

shape: (1, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│     ┆ Met ┆ Use ┆ Pra ┆ Cac ┆ Acc ┆ Acc ┆ Acc ┆ lan ┆ hos ┆ coo ┆ con ┆ con ┆ len ┆ con ┆ cla ┆ URL │
│ --- ┆ hod ┆ r-A ┆ gma ┆ he- ┆ ept ┆ ept ┆ ept ┆ gua ┆ t   ┆ kie ┆ ten ┆ nec ┆ ght ┆ ten ┆ ssi ┆ --- │
│ u32 ┆ --- ┆ gen ┆ --- ┆ Con ┆ --- ┆ -en ┆ -ch ┆ ge  ┆ --- ┆ --- ┆ t-t ┆ tio ┆ --- ┆ t   ┆ fic ┆ u32 │
│     ┆ u32 ┆ t   ┆ u32 ┆ tro ┆ u32 ┆ cod ┆ ars ┆ --- ┆ u32 ┆ u32 ┆ ype ┆ n   ┆ u32 ┆ --- ┆ ati ┆     │
│     ┆     ┆ --- ┆     ┆ l   ┆     ┆ ing ┆ et  ┆ u32 ┆     ┆     ┆ --- ┆ --- ┆     ┆ u32 ┆ on  ┆     │
│     ┆     ┆ u32 ┆     ┆ --- ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 397 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 430 ┆ 0   ┆ 430 ┆ 430 ┆ 0   ┆ 0   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 88  ┆     ┆ 88  ┆ 88  ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [5]:
df["lenght"].head

<bound method Series.head of shape: (61_065,)
Series: 'lenght' [str]
[
	null
	null
	"Content-Length: 68"
	null
	"Content-Length: 63"
	…
	null
	"Content-Length: 255"
	null
	null
	null
]>

#### First technical decision.

We are gonna transform null -> 0.

**¿ What does it implies?**

That we are going to have a pre-processing engine that tranform those request with no Content-Length to zero.

In [6]:
df= df.with_columns(
    pd.col("lenght")  # Using length column 
    .str.extract(r"(\d+)",1) # Extract digits using regular expressions
    .cast(pd.Int64, strict=False) # Transform those string digits to integers 64-bit
    .fill_null(0) # Filter where type is null, and convert it to zero.
)

# Showing results
df["lenght"].head()

shape: (10,)
Series: 'lenght' [i64]
[
	0
	0
	68
	0
	63
	0
	4
	0
	0
	33
]

In [7]:
df["content"].head

<bound method Series.head of shape: (61_065,)
Series: 'content' [str]
[
	null
	null
	"id=3&nombre=Vino+Rioja&precio=…
	null
	"modo=entrar&login=choong&pwd=d…
	…
	null
	"modo=registro&login=beaumont&p…
	null
	null
	null
]>

In [8]:
df= df.with_columns(
    pd.col("content")  # Using content column 
   .fill_null('') # Filter where type is null, and convert it to empty string.
)

# Showing results
df["content"].head()

shape: (10,)
Series: 'content' [str]
[
	""
	""
	"id=3&nombre=Vino+Rioja&precio=…
	""
	"modo=entrar&login=choong&pwd=d…
	""
	"id=2"
	""
	""
	"errorMsg=Credenciales+incorrec…
]

In [9]:
df= df.with_columns(
    pd.col("Accept")  # Using Accept column 
   .fill_null('') # Filter where Accept is null, and convert it to empty string.
)

# Showing results
df["Accept"].head()

shape: (10,)
Series: 'Accept' [str]
[
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
	"text/xml,application/xml,appli…
]

In [10]:
df["content-type"].head()

shape: (10,)
Series: 'content-type' [str]
[
	null
	null
	"application/x-www-form-urlenco…
	null
	"application/x-www-form-urlenco…
	null
	"application/x-www-form-urlenco…
	null
	null
	"application/x-www-form-urlenco…
]

In [11]:
df= df.with_columns(
    pd.col("content-type")  # Using Accept column 
   .fill_null('') # Filter where Accept is null, and convert it to empty string.
)

# Showing results
df["content-type"].head()

shape: (10,)
Series: 'content-type' [str]
[
	""
	""
	"application/x-www-form-urlenco…
	""
	"application/x-www-form-urlenco…
	""
	"application/x-www-form-urlenco…
	""
	""
	"application/x-www-form-urlenco…
]

### Showing results after cleaning up the dataset

In [12]:
with pd.Config(tbl_cols=17):
    print(df.null_count())

shape: (1, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│     ┆ Met ┆ Use ┆ Pra ┆ Cac ┆ Acc ┆ Acc ┆ Acc ┆ lan ┆ hos ┆ coo ┆ con ┆ con ┆ len ┆ con ┆ cla ┆ URL │
│ --- ┆ hod ┆ r-A ┆ gma ┆ he- ┆ ept ┆ ept ┆ ept ┆ gua ┆ t   ┆ kie ┆ ten ┆ nec ┆ ght ┆ ten ┆ ssi ┆ --- │
│ u32 ┆ --- ┆ gen ┆ --- ┆ Con ┆ --- ┆ -en ┆ -ch ┆ ge  ┆ --- ┆ --- ┆ t-t ┆ tio ┆ --- ┆ t   ┆ fic ┆ u32 │
│     ┆ u32 ┆ t   ┆ u32 ┆ tro ┆ u32 ┆ cod ┆ ars ┆ --- ┆ u32 ┆ u32 ┆ ype ┆ n   ┆ u32 ┆ --- ┆ ati ┆     │
│     ┆     ┆ --- ┆     ┆ l   ┆     ┆ ing ┆ et  ┆ u32 ┆     ┆     ┆ --- ┆ --- ┆     ┆ u32 ┆ on  ┆     │
│     ┆     ┆ u32 ┆     ┆ --- ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [13]:
df.head()

shape: (5, 17)
┌────────┬────────┬──────────────┬──────────┬───┬────────┬─────────────┬─────────────┬─────────────┐
│        ┆ Method ┆ User-Agent   ┆ Pragma   ┆ … ┆ lenght ┆ content     ┆ classificat ┆ URL         │
│ ---    ┆ ---    ┆ ---          ┆ ---      ┆   ┆ ---    ┆ ---         ┆ ion         ┆ ---         │
│ str    ┆ str    ┆ str          ┆ str      ┆   ┆ i64    ┆ str         ┆ ---         ┆ str         │
│        ┆        ┆              ┆          ┆   ┆        ┆             ┆ i64         ┆             │
╞════════╪════════╪══════════════╪══════════╪═══╪════════╪═════════════╪═════════════╪═════════════╡
│ Normal ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆             ┆ 0           ┆ http://loca │
│        ┆        ┆ (compatible; ┆          ┆   ┆        ┆             ┆             ┆ lhost:8080/ │
│        ┆        ┆ Konqu…       ┆          ┆   ┆        ┆             ┆             ┆ tienda1/…   │
│ Normal ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆             ┆ 0           ┆ http://loca │
│        ┆        ┆ (compatible; ┆          ┆   ┆        ┆             ┆             ┆ lhost:8080/ │
│        ┆        ┆ Konqu…       ┆          ┆   ┆        ┆             ┆             ┆ tienda1/…   │
│ Normal ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 68     ┆ id=3&nombre ┆ 0           ┆ http://loca │
│        ┆        ┆ (compatible; ┆          ┆   ┆        ┆ =Vino+Rioja ┆             ┆ lhost:8080/ │
│        ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ &precio=…   ┆             ┆ tienda1/…   │
│ Normal ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆             ┆ 0           ┆ http://loca │
│        ┆        ┆ (compatible; ┆          ┆   ┆        ┆             ┆             ┆ lhost:8080/ │
│        ┆        ┆ Konqu…       ┆          ┆   ┆        ┆             ┆             ┆ tienda1/…   │
│ Normal ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 63     ┆ modo=entrar ┆ 0           ┆ http://loca │
│        ┆        ┆ (compatible; ┆          ┆   ┆        ┆ &login=choo ┆             ┆ lhost:8080/ │
│        ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ ng&pwd=d…   ┆             ┆ tienda1/…   │
└────────┴────────┴──────────────┴──────────┴───┴────────┴─────────────┴─────────────┴─────────────┘

In [14]:
df = df.rename({"": "Label"})
print(df["Label"])

shape: (61_065,)
Series: 'Label' [str]
[
	"Normal"
	"Normal"
	"Normal"
	"Normal"
	"Normal"
	…
	"Anomalous"
	"Anomalous"
	"Anomalous"
	"Anomalous"
	"Anomalous"
]

In [15]:
df = df.with_columns(
    pd.col("Label")
    .replace({
        "Anomalous": 1,
        "Normal":0
    }).cast(pd.Int64, strict=False)
)

In [16]:
df.describe

<bound method DataFrame.describe of shape: (61_065, 17)
┌───────┬────────┬──────────────┬──────────┬───┬────────┬──────────────┬─────────────┬─────────────┐
│ Label ┆ Method ┆ User-Agent   ┆ Pragma   ┆ … ┆ lenght ┆ content      ┆ classificat ┆ URL         │
│ ---   ┆ ---    ┆ ---          ┆ ---      ┆   ┆ ---    ┆ ---          ┆ ion         ┆ ---         │
│ i64   ┆ str    ┆ str          ┆ str      ┆   ┆ i64    ┆ str          ┆ ---         ┆ str         │
│       ┆        ┆              ┆          ┆   ┆        ┆              ┆ i64         ┆             │
╞═══════╪════════╪══════════════╪══════════╪═══╪════════╪══════════════╪═════════════╪═════════════╡
│ 0     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 0     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 0     ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 68     ┆ id=3&nombre= ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆ Vino+Rioja&p ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ recio=…      ┆             ┆ tienda1/…   │
│ 0     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 0     ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 63     ┆ modo=entrar& ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆ login=choong ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ &pwd=d…      ┆             ┆ tienda1/…   │
│ …     ┆ …      ┆ …            ┆ …        ┆ … ┆ …      ┆ …            ┆ …           ┆ …           │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 1     ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 255    ┆ modo=registr ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆ o&login=beau ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ mont&p…      ┆             ┆ tienda1/…   │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
└───────┴────────┴──────────────┴──────────┴───┴────────┴──────────────┴─────────────┴─────────────┘>

In [17]:
df.describe

<bound method DataFrame.describe of shape: (61_065, 17)
┌───────┬────────┬──────────────┬──────────┬───┬────────┬──────────────┬─────────────┬─────────────┐
│ Label ┆ Method ┆ User-Agent   ┆ Pragma   ┆ … ┆ lenght ┆ content      ┆ classificat ┆ URL         │
│ ---   ┆ ---    ┆ ---          ┆ ---      ┆   ┆ ---    ┆ ---          ┆ ion         ┆ ---         │
│ i64   ┆ str    ┆ str          ┆ str      ┆   ┆ i64    ┆ str          ┆ ---         ┆ str         │
│       ┆        ┆              ┆          ┆   ┆        ┆              ┆ i64         ┆             │
╞═══════╪════════╪══════════════╪══════════╪═══╪════════╪══════════════╪═════════════╪═════════════╡
│ 0     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 0     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 0     ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 68     ┆ id=3&nombre= ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆ Vino+Rioja&p ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ recio=…      ┆             ┆ tienda1/…   │
│ 0     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 0     ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 63     ┆ modo=entrar& ┆ 0           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆ login=choong ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ &pwd=d…      ┆             ┆ tienda1/…   │
│ …     ┆ …      ┆ …            ┆ …        ┆ … ┆ …      ┆ …            ┆ …           ┆ …           │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 1     ┆ POST   ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 255    ┆ modo=registr ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆ o&login=beau ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆ mont&p…      ┆             ┆ tienda1/…   │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
│ 1     ┆ GET    ┆ Mozilla/5.0  ┆ no-cache ┆ … ┆ 0      ┆              ┆ 1           ┆ http://loca │
│       ┆        ┆ (compatible; ┆          ┆   ┆        ┆              ┆             ┆ lhost:8080/ │
│       ┆        ┆ Konqu…       ┆          ┆   ┆        ┆              ┆             ┆ tienda1/…   │
└───────┴────────┴──────────────┴──────────┴───┴────────┴──────────────┴─────────────┴─────────────┘>

In [18]:
import urllib

def decode_url(val: str) -> str:
    return urllib.parse.unquote(val).strip() if val else ""

In [19]:
df = df.with_columns(
    pd.col("URL")
    .map_elements(decode_url, return_dtype=pd.String)
    .alias("URL_decoded")

)

In [20]:
with pd.Config(tbl_cols=18):
    print(df.describe)

<bound method DataFrame.describe of shape: (61_065, 18)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Lab ┆ Met ┆ Use ┆ Pra ┆ Cac ┆ Acc ┆ Acc ┆ Acc ┆ lan ┆ hos ┆ coo ┆ con ┆ con ┆ len ┆ con ┆ cla ┆ URL ┆ URL │
│ el  ┆ hod ┆ r-A ┆ gma ┆ he- ┆ ept ┆ ept ┆ ept ┆ gua ┆ t   ┆ kie ┆ ten ┆ nec ┆ ght ┆ ten ┆ ssi ┆ --- ┆ _de │
│ --- ┆ --- ┆ gen ┆ --- ┆ Con ┆ --- ┆ -en ┆ -ch ┆ ge  ┆ --- ┆ --- ┆ t-t ┆ tio ┆ --- ┆ t   ┆ fic ┆ str ┆ cod │
│ i64 ┆ str ┆ t   ┆ str ┆ tro ┆ str ┆ cod ┆ ars ┆ --- ┆ str ┆ str ┆ ype ┆ n   ┆ i64 ┆ --- ┆ ati ┆     ┆ ed  │
│     ┆     ┆ --- ┆     ┆ l   ┆     ┆ ing ┆ et  ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆ on  ┆     ┆ --- │
│     ┆     ┆ str ┆     ┆ --- ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ --- ┆     ┆ str │
│     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ GET ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆     ┆ clo ┆ 0   ┆     ┆ 0   ┆ htt ┆ htt │
│     ┆     ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆     ┆ se  ┆     ┆     ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆     ┆     ┆     ┆     ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=1 ┆     ┆     ┆     ┆     ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ F76 ┆     ┆     ┆     ┆     ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ 7F1 ┆     ┆     ┆     ┆     ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ 723 ┆     ┆     ┆     ┆     ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ 9C9 ┆     ┆     ┆     ┆     ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ B67 ┆     ┆     ┆     ┆     ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 0A3 ┆     ┆     ┆     ┆     ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   │
│ 0   ┆ GET ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆     ┆ clo ┆ 0   ┆     ┆ 0   ┆ htt ┆ htt │
│     ┆     ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆     ┆ se  ┆     ┆     ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆     ┆     ┆     ┆     ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=8 ┆     ┆     ┆     ┆     ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ 176 ┆     ┆     ┆     ┆     ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ 1AC ┆     ┆     ┆     ┆     ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ A04 ┆     ┆     ┆     ┆     ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ 3B0 ┆     ┆     ┆     ┆     ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ E60 ┆     ┆     ┆     ┆     ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 14C ┆     ┆     ┆     ┆     ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   │
│ 0   ┆ POS ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆ app ┆ Con ┆ 68  ┆ id= ┆ 0   ┆ htt ┆ htt │
│     ┆ T   ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆ lic ┆ nec ┆     ┆ 3&n ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆ ati ┆ tio ┆     ┆ omb ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=9 ┆ on/ ┆ n:  ┆     ┆ re= ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ 331 ┆ x-w ┆ clo ┆     ┆ Vin ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ 850 ┆ ww- ┆ se  ┆     ┆ o+R ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ 92E ┆ for ┆     ┆     ┆ ioj ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ 0B6 ┆ m-u ┆     ┆     ┆ a&p ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ 68B ┆ rle ┆     ┆     ┆ rec ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 906 ┆ nco ┆     ┆     ┆ io= ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆ …   ┆     ┆ …   ┆ …   │
│ 0   ┆ GET ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆     ┆ clo ┆ 0   ┆     ┆ 0   ┆ htt ┆ htt │
│     ┆     ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆     ┆ se  ┆     ┆     ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆     ┆     ┆     ┆     ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=8 ┆     ┆     ┆     ┆     ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ FA1 ┆     ┆     ┆     ┆     ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ 8BA ┆     ┆     ┆     ┆     ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ 82C ┆     ┆     ┆     ┆     ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ 533 ┆     ┆     ┆     ┆     ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ 6D0 ┆     ┆     ┆     ┆     ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 3D3 ┆     ┆     ┆     ┆     ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   │
│ 0   ┆ POS ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆ app ┆ Con ┆ 63  ┆ mod ┆ 0   ┆ htt ┆ htt │
│     ┆ T   ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆ lic ┆ nec ┆     ┆ o=e ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆ ati ┆ tio ┆     ┆ ntr ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=7 ┆ on/ ┆ n:  ┆     ┆ ar& ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ 104 ┆ x-w ┆ clo ┆     ┆ log ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ E6C ┆ ww- ┆ se  ┆     ┆ in= ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ 68A ┆ for ┆     ┆     ┆ cho ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ 6BC ┆ m-u ┆     ┆     ┆ ong ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ F14 ┆ rle ┆     ┆     ┆ &pw ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 23D ┆ nco ┆     ┆     ┆ d=d ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆ …   ┆     ┆ …   ┆ …   │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 1   ┆ GET ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆     ┆ clo ┆ 0   ┆     ┆ 1   ┆ htt ┆ htt │
│     ┆     ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆     ┆ se  ┆     ┆     ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆     ┆     ┆     ┆     ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=6 ┆     ┆     ┆     ┆     ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ 221 ┆     ┆     ┆     ┆     ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ 6AD ┆     ┆     ┆     ┆     ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ BBD ┆     ┆     ┆     ┆     ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ 9B9 ┆     ┆     ┆     ┆     ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ 1E1 ┆     ┆     ┆     ┆     ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 7CA ┆     ┆     ┆     ┆     ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   │
│ 1   ┆ POS ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆ app ┆ Con ┆ 255 ┆ mod ┆ 1   ┆ htt ┆ htt │
│     ┆ T   ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆ lic ┆ nec ┆     ┆ o=r ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆ ati ┆ tio ┆     ┆ egi ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=2 ┆ on/ ┆ n:  ┆     ┆ str ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ 317 ┆ x-w ┆ clo ┆     ┆ o&l ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ F5C ┆ ww- ┆ se  ┆     ┆ ogi ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ 0B1 ┆ for ┆     ┆     ┆ n=b ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ B7F ┆ m-u ┆     ┆     ┆ eau ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ AD1 ┆ rle ┆     ┆     ┆ mon ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 8EB ┆ nco ┆     ┆     ┆ t&p ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆ …   ┆     ┆ …   ┆ …   │
│ 1   ┆ GET ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆     ┆ clo ┆ 0   ┆     ┆ 1   ┆ htt ┆ htt │
│     ┆     ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆     ┆ se  ┆     ┆     ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆     ┆     ┆     ┆     ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=7 ┆     ┆     ┆     ┆     ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ F0B ┆     ┆     ┆     ┆     ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ A54 ┆     ┆     ┆     ┆     ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ A88 ┆     ┆     ┆     ┆     ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ B84 ┆     ┆     ┆     ┆     ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ 9EF ┆     ┆     ┆     ┆     ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 752 ┆     ┆     ┆     ┆     ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   │
│ 1   ┆ GET ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆     ┆ clo ┆ 0   ┆     ┆ 1   ┆ htt ┆ htt │
│     ┆     ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆     ┆ se  ┆     ┆     ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆     ┆     ┆     ┆     ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=F ┆     ┆     ┆     ┆     ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ B01 ┆     ┆     ┆     ┆     ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ 8FF ┆     ┆     ┆     ┆     ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ B06 ┆     ┆     ┆     ┆     ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ 011 ┆     ┆     ┆     ┆     ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ CFA ┆     ┆     ┆     ┆     ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ BD6 ┆     ┆     ┆     ┆     ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   │
│ 1   ┆ GET ┆ Moz ┆ no- ┆ no- ┆ tex ┆ x-g ┆ utf ┆ en  ┆ loc ┆ JSE ┆     ┆ clo ┆ 0   ┆     ┆ 1   ┆ htt ┆ htt │
│     ┆     ┆ ill ┆ cac ┆ cac ┆ t/x ┆ zip ┆ -8, ┆     ┆ alh ┆ SSI ┆     ┆ se  ┆     ┆     ┆     ┆ p:/ ┆ p:/ │
│     ┆     ┆ a/5 ┆ he  ┆ he  ┆ ml, ┆ ,   ┆ utf ┆     ┆ ost ┆ ONI ┆     ┆     ┆     ┆     ┆     ┆ /lo ┆ /lo │
│     ┆     ┆ .0  ┆     ┆     ┆ app ┆ x-d ┆ -8; ┆     ┆ :80 ┆ D=3 ┆     ┆     ┆     ┆     ┆     ┆ cal ┆ cal │
│     ┆     ┆ (co ┆     ┆     ┆ lic ┆ efl ┆ q=0 ┆     ┆ 80  ┆ CC1 ┆     ┆     ┆     ┆     ┆     ┆ hos ┆ hos │
│     ┆     ┆ mpa ┆     ┆     ┆ ati ┆ ate ┆ .5, ┆     ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆ t:8 ┆ t:8 │
│     ┆     ┆ tib ┆     ┆     ┆ on/ ┆ ,   ┆ *;q ┆     ┆     ┆ 0CD ┆     ┆     ┆     ┆     ┆     ┆ 080 ┆ 080 │
│     ┆     ┆ le; ┆     ┆     ┆ xml ┆ gzi ┆ =0. ┆     ┆     ┆ A95 ┆     ┆     ┆     ┆     ┆     ┆ /ti ┆ /ti │
│     ┆     ┆ Kon ┆     ┆     ┆ ,ap ┆ p,  ┆ 5   ┆     ┆     ┆ 2F1 ┆     ┆     ┆     ┆     ┆     ┆ end ┆ end │
│     ┆     ┆ qu… ┆     ┆     ┆ pli ┆ def ┆     ┆     ┆     ┆ 232 ┆     ┆     ┆     ┆     ┆     ┆ a1/ ┆ a1/ │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ la… ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘>

In [21]:
df["connection"].head

df = df.with_columns(
    pd.col('connection')
    .str.replace('Connection: ', "")
)

In [22]:
df['connection'].head

<bound method Series.head of shape: (61_065,)
Series: 'connection' [str]
[
	"close"
	"close"
	"close"
	"close"
	"close"
	…
	"close"
	"close"
	"close"
	"close"
	"close"
]>

In [23]:
df.schema

Schema([('Label', Int64),
        ('Method', String),
        ('User-Agent', String),
        ('Pragma', String),
        ('Cache-Control', String),
        ('Accept', String),
        ('Accept-encoding', String),
        ('Accept-charset', String),
        ('language', String),
        ('host', String),
        ('cookie', String),
        ('content-type', String),
        ('connection', String),
        ('lenght', Int64),
        ('content', String),
        ('classification', Int64),
        ('URL', String),
        ('URL_decoded', String)])

This is the final on standarizing and normalizing data, now the target is to convert this raw strings into embbedings.
We are going to do that all in memory, that because we can load all dataset into memory because it only 30MB wich means it is relatibily small and we can finally save taht into a file Parquet.

If this dataset would be Gigabytes of size we should process it into chunks and writting the file in execution.

In [24]:
df.write_parquet("csic_cleaned.parquet")